#ifndef FONT_H
#define FONT_H

#include <map>

#include "Glyph.h"

namespace re {

/**
 * @brief The FontType enum
 * different type of font have different depth and texture format, they
 * will use different shader normally
 *
 * TTF: generated from ttf on the fly, depth is 1, texture formate TextureFormat::RED
 * Bitmap: generated by GlyphDesigner and so on, depth is 4, texture formate TextureFormat::RGBA8
 */
enum class FontType
{
    TTF,
    Bitmap,
};

class Font : public Named, public Shared<Font>
{
public:
    Font(FontType type, Int size, const FilePtr& file);

    ~Font();

public:
    Glyph::constPtr getGlyph(const wchar_t& c) const;
    void addGlyph(Glyph::ptr& glyph);

    FontType getType() const;
    Int getSize() const;

    const std::map<wchar_t, Glyph::ptr>& getAllGlyphs();

    /**
     * @brief getTexture
     * @return
     *
     * TODO: one font can have two or more texture?
     */
    Texture::ptr getTexture();

protected:
    FontType type;

    /**
     * @brief size
     * font size, size of glyph
     */
    Int size;

    std::map<wchar_t, Glyph::ptr> glyphs;

public:
    FilePtr file;
};

}

#endif // FONT_H
